### ISSUE TITLE
Installing radon breaks flake8

### ISSUE THREAD

**Issue by joxl** [rubik/radon#217] opened 2021-05-11 00:40 UTC
## Issue

The radon `setup.py` configures `entry_points` for flake8.  When used by flake8,
this entry point attempts to unconditionally import `flake8_polyfill`, causing
flake8 to crash due to an `ImportError` if flake8-polyfill is not installed.

The radon library should either specify `flake8-polyfill` as a required
dependency, or guard against this error condition.

## Steps to reproduce

1. Create a new virtualenv (`pyenv-virtualenv` used in this example):

    ```bash
    $ pyenv virtualenv 3.6.13 radon-issue
    $ pyenv activate radon-issue
    ```

2. Install flake8 and observe only flake8 and dependencies are installed:

    ```bash
    $ pip install flake8
    $ pip freeze
    flake8==3.9.2
    importlib-metadata==4.0.1
    mccabe==0.6.1
    pycodestyle==2.7.0
    pyflakes==2.3.1
    typing-extensions==3.10.0.0
    zipp==3.4.1
    ```

3. Confirm flake8 works (`--version` option used for this purpose):

    ```bash
    $ flake8 --version
    3.9.2 (mccabe: 0.6.1, pycodestyle: 2.7.0, pyflakes: 2.3.1) CPython 3.6.13 on
    Linux
    ```

4. Install radon and observe new installed libraries:

    ```bash
    $ pip install radon
    $ pip freeze
    colorama==0.4.4
    flake8==3.9.2
    future==0.18.2
    importlib-metadata==4.0.1
    mando==0.6.4
    mccabe==0.6.1
    pycodestyle==2.7.0
    pyflakes==2.3.1
    radon==4.5.1
    six==1.16.0
    typing-extensions==3.10.0.0
    zipp==3.4.1
    ```

5. Run flake8 again:

    ```python
    $ flake8 --version
    Traceback (most recent call last):
    File "/home/user/.pyenv/versions/3.6.13/envs/radon-issue/lib/python3.6/site-packages/flake8/plugins/manager.py", line 157, in load_plugin
        self._load()
    File "/home/user/.pyenv/versions/3.6.13/envs/radon-issue/lib/python3.6/site-packages/flake8/plugins/manager.py", line 134, in _load
        self._plugin = self.entry_point.load()
    File "/home/user/.pyenv/versions/3.6.13/envs/radon-issue/lib/python3.6/site-packages/importlib_metadata/__init__.py", line 166, in load
        module = import_module(match.group('module'))
    File "/home/user/.pyenv/versions/3.6.13/lib/python3.6/importlib/__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
    File "<frozen importlib._bootstrap>", line 994, in _gcd_import
    File "<frozen importlib._bootstrap>", line 971, in _find_and_load
    File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
    File "<frozen importlib._bootstrap_external>", line 678, in exec_module
    File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
    File "/home/user/.pyenv/versions/3.6.13/envs/radon-issue/lib/python3.6/site-packages/radon/contrib/flake8.py", line 1, in <module>
        from flake8_polyfill import options
    ModuleNotFoundError: No module named 'flake8_polyfill'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
    File "/home/user/.pyenv/versions/radon-issue/bin/flake8", line 11, in <module>
        sys.exit(main())
    File "/home/user/.pyenv/versions/3.6.13/envs/radon-issue/lib/python3.6/site-packages/flake8/main/cli.py", line 22, in main
        app.run(argv)
    File "/home/user/.pyenv/versions/3.6.13/envs/radon-issue/lib/python3.6/site-packages/flake8/main/application.py", line 363, in run
        self._run(argv)
    File "/home/user/.pyenv/versions/3.6.13/envs/radon-issue/lib/python3.6/site-packages/flake8/main/application.py", line 350, in _run
        self.initialize(argv)
    File "/home/user/.pyenv/versions/3.6.13/envs/radon-issue/lib/python3.6/site-packages/flake8/main/application.py", line 330, in initialize
        self.find_plugins(config_finder)
    File "/home/user/.pyenv/versions/3.6.13/envs/radon-issue/lib/python3.6/site-packages/flake8/main/application.py", line 159, in find_plugins
        self.check_plugins.load_plugins()
    File "/home/user/.pyenv/versions/3.6.13/envs/radon-issue/lib/python3.6/site-packages/flake8/plugins/manager.py", line 415, in load_plugins
        plugins = list(self.manager.map(load_plugin))
    File "/home/user/.pyenv/versions/3.6.13/envs/radon-issue/lib/python3.6/site-packages/flake8/plugins/manager.py", line 302, in map
        yield func(self.plugins[name], *args, **kwargs)
    File "/home/user/.pyenv/versions/3.6.13/envs/radon-issue/lib/python3.6/site-packages/flake8/plugins/manager.py", line 413, in load_plugin
        return plugin.load_plugin()
    File "/home/user/.pyenv/versions/3.6.13/envs/radon-issue/lib/python3.6/site-packages/flake8/plugins/manager.py", line 164, in load_plugin
        raise failed_to_load
    flake8.exceptions.FailedToLoadPlugin: Flake8 failed to load plugin "R70" due to No module named 'flake8_polyfill'.
    ```

### Observe

Command `flake8 --version` crashes due to `ImportError` when radon is installed.

### Expected

Command `flake8 --version` outputs version information and exits cleanly.

**Comment by joxl** [comment] 2021-05-14 04:00
It looks like this configuration was assumed safe when explained here: https://github.com/rubik/radon/issues/189#issuecomment-687786399

> So, `flake8` will be able to import entry point without any issues.

Which is **only** true if `flake8-polyfill` was first installed some way or another.

Since flake8 executes exposed entry points *every time* it runs, the unguarded `flake8_polyfill` import causes flake8 to crash. This prevents a project from using both `flake8` *and* `radon` without explicitly installing the radon extra (i.e. via `radon[flake8]`) or `flake8-polyfill` by some other means.

**Comment by rubik** [comment] 2021-05-17 13:16
@joxl Indeed, you should install `radon[flake8]` if you plan to use it in combination with Flake8. Apart from that, it's quite inconvenient that flake8 breaks if Radon is installed manually. What about: (1) clarifying that in the documentation and (2) check the flake8-polyfill for an `ImportError` and display a suitable error message?

**Comment by joxl** [comment] 2021-05-17 19:17
> What about: (1) clarifying that in the documentation and (2) check the flake8-polyfill for an ImportError and display a suitable error message?

This is would make it easier for unsuspecting project owners to debug the problem (that Radon is not using the `flake8.extension` entry point correctly); which is helpful in some way I suppose, but not very.

The problem is that Radon breaks flake8 even when the project that installs it doesn't need to use Radon's flake8 extension (e.g. `pip install radon`).

I've looked into why the CI testing isn't discovering this bug, and I've identified two possible scenarios, but the TL;DR is because there are no tests run *without* `flake8-polyfill` installed. Determining whether that's correct or not depends on which scenario is desired.

The two scenarios I can think of imply that there is either (1) a `setup.py` bug, or (2) a `radon/contrib/flake8.py` bug and inadequate testing.

1. **(bug in `setup.py`)** As the setup.py is currently written, using this library without wanting to use the "extras" is a completely valid configuration (that's why they're extras).  If this is *not* a valid configuration, then the flake8-polyfill dependency should be moved out of `extras_require` and into `install_requires`. This would ensure that Radon *cannot* be installed without flake8-polyfill, and thus never be able to break flake8.
2. **(bug in `radon/contrib/flake8.py` and inadequate testing)** If the flake8-polyfill dependency is to remain an extra-only dependency, then I think there should be two CI jobs. One that tests the package *with* the extra, and one that tests it without. This would make it clear that `radon/contrib/flake8.py` needs to catch and handle the `ImportError` so projects that wish to use Radon without the extra can still use flake8 without having flake8-polyfill installed.

**Comment by rubik** [comment] 2021-05-23 07:08
@joxl I wanted to first reproduce the bug but I could not verify it. Here's what I did:

```sh
$  pip freeze
$ pip install flake8
Collecting flake8
  Using cached flake8-3.9.2-py2.py3-none-any.whl (73 kB)
Collecting pyflakes<2.4.0,>=2.3.0
  Using cached pyflakes-2.3.1-py2.py3-none-any.whl (68 kB)
Collecting pycodestyle<2.8.0,>=2.7.0
  Using cached pycodestyle-2.7.0-py2.py3-none-any.whl (41 kB)
Collecting mccabe<0.7.0,>=0.6.0
  Using cached mccabe-0.6.1-py2.py3-none-any.whl (8.6 kB)
Installing collected packages: pyflakes, pycodestyle, mccabe, flake8
Successfully installed flake8-3.9.2 mccabe-0.6.1 pycodestyle-2.7.0 pyflakes-2.3.1
$ pip freeze
flake8==3.9.2
mccabe==0.6.1
pycodestyle==2.7.0
pyflakes==2.3.1
$ flake8 --version
3.8.4 (mccabe: 0.6.1, pycodestyle: 2.6.0, pyflakes: 2.2.0) CPython 3.9.5 on Linux
$ pip install radon
Collecting radon
  Using cached radon-4.5.1-py2.py3-none-any.whl (51 kB)
Collecting colorama>=0.4.1
  Using cached colorama-0.4.4-py2.py3-none-any.whl (16 kB)
Collecting mando<0.7,>=0.6
  Using cached mando-0.6.4-py2.py3-none-any.whl (29 kB)
Collecting future
  Using cached future-0.18.2-py3-none-any.whl
Collecting six
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Installing collected packages: six, mando, future, colorama, radon
Successfully installed colorama-0.4.4 future-0.18.2 mando-0.6.4 radon-4.5.1 six-1.16.0
$ pip freeze
colorama==0.4.4
flake8==3.9.2
future==0.18.2
mando==0.6.4
mccabe==0.6.1
pycodestyle==2.7.0
pyflakes==2.3.1
radon==4.5.1
six==1.16.0
$ flake8 --version
3.8.4 (mccabe: 0.6.1, pycodestyle: 2.6.0, pyflakes: 2.2.0) CPython 3.9.5 on Linux
```

The main difference between our two environments is Python. You tested this on Python 3.6, while I'm using 3.9. There are also some other oddities: according to `pip freeze`, flake8 version 3.9.2 is installed (like in your test), but running `flake8 --version` displays 3.8.4?! pycodestyle and pyflakes also show a different version than Pip. This calls for more testing.

**Comment by rubik** [comment] 2021-05-23 07:21
@joxl I reproduced your bug report by running the same commands, then I tested the same configuration by adding a suitable error message if `flake8-polyfill` is not found. The result isn't much different. The message is buried in a long traceback that flake8 displays on every command.

Since that's not user-friendly at all, I decided that `flake8-polyfill` will be moved back into `install_requires`. I am not a fan of useless dependencies but in this case usability comes first. I would even say that this is a bug on flake8's side: if a plugin fails to load in the import phase it should show a warning/error message and simply continue without it. Making everything fail for no reason does not seem like a good decision.

In any case, it will be first fixed on Radon's side by removing the extra.

**Comment by rubik** [comment] 2021-05-23 07:38
@joxl I verified that flake8 is no longer broken when radon is installed with the pre-release 4.5.2.dev0. I will now make an official release.

**Comment by rubik** [comment] 2021-05-23 07:40
@joxl Radon 4.5.2 is now on PyPI. Thanks for reporting this issue.

**Closed** 2021-05-23 07:39 UTC

**Comment by joxl** [comment] 2021-05-23 18:35
Thanks for the fix, @rubik.  I agree, leaving flake8-polyfill as a hard requirement feels a bit heavy.  I don't know how much longer Flake8 2.x will be supported, one solution would be for Radon to just drop support for it in order to remove the need for flake8-polyfill completely (I'm not sure how appealing that is to the Radon project).

I started working on a solution that kept flake8-polyfill as an extra, my thought process was to catch the ImportError and define a flake8 plugin "stub" that was disabled and would raise an error if you try to explicitly enable it.  Something along the lines of:

```python
# radon/contrib/flake8.py
try:
    from flake8_polyfill import options
except ImportError:
    class ExtensionRequiresExtraError(Exception):
        pass
    options = None

# snip...

class Flake8Checker(object):
    '''Entry point for the Flake8 tool.'''

    if options is None:
        name = "radon_noop"
        version = None
        off_by_default = True

        def run(self):
            raise ExtensionRequiresExtraError('The radon extension for flake8 '
                                              'requires installing extras.')
    else:
        name = 'radon'
        # snip...
        def __init__(self, ...
```

I began writing this and realized that the flake8 extension manger logic is doing strange stuff that I was not expecting (e.g. analyzing the argument names of plugin `__init__` methods), and I don't even know if a "dummy plugin" is even a reasonable thing to do. Unfortunately this requires a deeper dive into flake8 to understand if there can be an elegant way to do this, which is a larger scope than I had anticipated.

**Comment by rubik** [comment] 2021-05-24 06:45
@joxl That was an interesting try! I think it's time to drop support for Flake8 version 2. Checking on PyPI, I see that Flake8 v2.6 was released in 2016, and flake8-polyfill's last release is in 2017. We can bump Radon's major version to 5, drop support for Flake8 2 and remove flake8-polyfill. I just need to check if we need to change the way plugin options are added. That way, if someone wants to use Radon with Flake8 version 2, they can just use the 4.5.2 version.
