### ISSUE TITLE
python3: Do not understand cyrillic sybols

### ISSUE THREAD

**Issue by SowingSadness** [rubik/radon#94] opened 2016-10-28 16:15 UTC
``` python3
class Foo:
   def метод(self):
      pass


bar = Foo()
bar.метод()
```

> radon cc t.py -a t.py
>     ERROR: invalid character in identifier (<unknown>, line 2)

**Comment by rubik** [comment] 2016-10-29 07:09
Cannot reproduce. You are most likely using Python 2, because this is what I get on Python 3:
$ radon cc cyr.py
cyr.py
    C 1:0 Foo - A
    M 2:3 Foo.метод - A
$ python cyr.py
$ python2 cyr.py
  File cyr.py, line 2
SyntaxError: Non-ASCII character '�' in file cyr.py on line 2, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
```

**Comment by SowingSadness** [comment] 2016-10-30 08:31
Reproduce windows only :)

![screenshot_2](https://cloud.githubusercontent.com/assets/576443/19835290/434a0112-9e92-11e6-9502-0abba6a98a86.png)

same PC, but in windows subsystem linux:
![screenshot_3](https://cloud.githubusercontent.com/assets/576443/19835337/43699444-9e94-11e6-9729-8f96af81b6b4.png)

**Comment by rubik** [comment] 2016-10-30 08:53
Ah, Windows, I see. I think it could be that the default encoding on Windows does not have Cyrillic symbols, and Radon is using that one. I shall investigate.

**Comment by SowingSadness** [comment] 2016-10-30 09:01
@rubik default encoding in windows - cp1251. But all examples in UTF8 )

**Comment by rubik** [comment] 2016-12-18 09:09
Closed by #99. Can you retry by setting `RADONFILESENCODING=utf-8`?

**Closed by rubik** 2016-12-18 09:09 UTC

**Comment by SowingSadness** [comment] 2016-12-18 09:53
@rubik I don't know is right version in PyPi or nor.
![image](https://cloud.githubusercontent.com/assets/576443/21292774/e9da73f4-c520-11e6-88cf-89d5aafa3488.png)

**Comment by rubik** [comment] 2016-12-18 10:16
No, it's not on PyPI yet, you should install from master.
